name: emush

services:
  emush-web:
    container_name: emush-web
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - 8080:80
    networks:
      - emush-network
    restart: unless-stopped
    depends_on:
      - emush-api
    volumes:
      - api-public:/var/www/html/public:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS -o /dev/null http://localhost/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
  
  emush-app:
    container_name: emush-app
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 5173:5173
    networks:
      - emush-network
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - emush-web
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  emush-api:
    container_name: emush-api
    build:
      context: .
      dockerfile: Dockerfile.api
    expose:
      - 9000
    networks:
      - emush-network
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - emush-database
    volumes:
      - api-public:/var/www/html/public
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  emush-database:
    container_name: emush-database
    build:
      context: .
      dockerfile: Dockerfile.db
    networks:
      - emush-network
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: emush
      POSTGRES_PASSWORD: emush_password
      POSTGRES_DB: emush
      POSTGRES_MULTIPLE_DATABASES: eternaltwin.prod
    volumes:
      - emush-database-data:/var/lib/postgresql/data
      - ./database-init.sh:/docker-entrypoint-initdb.d/database-init.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U emush -d emush"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  emush-eternaltwin:
    container_name: emush-eternaltwin
    build:
      context: .
      dockerfile: Dockerfile.eternaltwin
    depends_on:
      - emush-database
    networks:
      - emush-network
    ports:
      - 50320:50320
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS -o /dev/null http://localhost:50320/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  emush-database-data:
    driver: local
  api-public:
    driver: local

networks:
  emush-network:
    driver: bridge
