name: emush

services:
  emush-web:
    container_name: emush-web
    build:
      context: .
      dockerfile: Dockerfile.web
    networks:
      - emush-network
      - traefik-proxy
    restart: unless-stopped
    depends_on:
      emush-api:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.emush-web.rule=Host(`api.emush.${DOMAIN}`)
      - traefik.http.routers.emush-web.entrypoints=websecure
      - traefik.http.routers.emush-web.tls.certresolver=letsencrypt
      - traefik.http.services.emush-web.loadbalancer.server.port=80
      - traefik.docker.network=traefik-proxy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS -o /dev/null http://localhost/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
  
  emush-app:
    container_name: emush-app
    build:
      context: .
      dockerfile: Dockerfile.app
    networks:
      - emush-network
      - traefik-proxy
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      emush-web:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.emush-app.rule=Host(`emush.${DOMAIN}`)
      - traefik.http.routers.emush-app.entrypoints=websecure
      - traefik.http.routers.emush-app.tls.certresolver=letsencrypt
      - traefik.http.services.emush-app.loadbalancer.server.port=5173
      - traefik.docker.network=traefik-proxy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  emush-api:
    container_name: emush-api
    build:
      context: .
      dockerfile: Dockerfile.api
    networks:
      - emush-network
      - traefik-proxy
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - emush-database
    volumes:
      - jwt-keys:/var/www/html/config/jwt
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  emush-database:
    container_name: emush-database
    build:
      context: .
      dockerfile: Dockerfile.db
    networks:
      - emush-network
    restart: unless-stopped
    environment:
      POSTGRES_USER: emush
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: emush
      POSTGRES_MULTIPLE_DATABASES: eternaltwin.prod
    volumes:
      - emush-database-data:/var/lib/postgresql/data
      - ./database-init.sh:/docker-entrypoint-initdb.d/database-initdb.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U emush -d emush"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  emush-eternaltwin:
    container_name: emush-eternaltwin
    build:
      context: .
      dockerfile: Dockerfile.eternaltwin
      args:
        UID: ${UID:-1000}
        GID: ${UID:-1000}
    depends_on:
      - emush-database
    networks:
      - emush-network
      - traefik-proxy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS -o /dev/null http://localhost:50320/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
      - traefik.enable=true
      - traefik.http.routers.emush-eternaltwin.rule=Host(`eternaltwin.${DOMAIN}`)
      - traefik.http.routers.emush-eternaltwin.entrypoints=websecure
      - traefik.http.routers.emush-eternaltwin.tls.certresolver=letsencrypt
      - traefik.http.services.emush-eternaltwin.loadbalancer.server.port=50320
      - traefik.docker.network=traefik-proxy

  emush-jaeger:
    container_name: emush-jaeger
    image: jaegertracing/jaeger:2.11.0
    networks:
      - emush-network
      - traefik-proxy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:13133/status"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
      - traefik.enable=true
      - traefik.http.routers.emush-jaeger.rule=Host(`jaeger.emush.${DOMAIN}`)
      - traefik.http.routers.emush-jaeger.entrypoints=websecure
      - traefik.http.routers.emush-jaeger.tls.certresolver=letsencrypt
      - traefik.http.services.emush-jaeger.loadbalancer.server.port=16686
      - traefik.docker.network=traefik-proxy

volumes:
  emush-database-data:
    driver: local
  jwt-keys:
    driver: local

networks:
  emush-network:
    driver: bridge
  traefik-proxy:
    external: true

