FROM node:lts-slim

ARG UID=$UID
ARG GID=$GID

WORKDIR /www

RUN apt-get update && apt-get install -y curl

COPY emush/Eternaltwin/ ./

RUN corepack enable && yarn install --immutable

RUN usermod -u ${UID} -g ${GID} node && chown -R node:node /www

USER node

CMD ["yarn", "eternaltwin", "start"]