[backend]
store = "Postgres"

[postgres]
host = "emush-database"
port = 5432
name = "eternaltwin.prod"
user = "emush"
password = "emush_password"

[seed.app.emush_production]
display_name = "eMush"
uri = "http://localhost/"
oauth_callback = "http://localhost:8080/oauth/callback"
secret = "my_super_eternaltwin_oauth_secret"

[seed.user.admin]
username = "admin"
password = "9yD5hiim2BbVGLH"