name: Deploy

on:
  schedule:
    - cron: '0 3 * * *' # Tous les jours à 3AM UTC
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Check for eMush updates
        id: check
        run: ./.github/scripts/check-for-emush-updates.sh

      - name: Deploy eMush
        if: steps.check.outputs.updated == 'true'
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: cd www && make deploy-beta